### ISSUE TITLE
Gleam removed gleam/erlang/file

### ISSUE THREAD

**Issue by tankorsmash** [Grubba27/gleam_dotenv#3]
Was looking to use this package on a recent Gleam, and found it doesn't compile :(

File IO was removed in v0.26 it looks like 

https://github.com/gleam-lang/erlang/commit/0ad27f2d4bbbcb765b3f62a6b1e20c14596ebc66

**Comment by tankorsmash** [comment]
Adding the `simplifile` package and changing `file.read` to `simplifile.read` seems to compile and read the dotenv great!

**Comment by Grubba27** [comment]
Oh, sounds good! could you mind making a pr for that?

**Comment by tankorsmash** [comment]
https://github.com/Grubba27/dotenv_gleam/pull/4 done! Let me know if there's anything I should change
